# gpio
PIN_OUT_INVADED = 21
PIN_OUT_TIMEOUT = 20
PIN_IN_EMERGENCY = 16

# serial
SERIAL_DEVICE_PATH   = '/dev/ttyS0'
SERIAL_BAUDRATE = 9600

# face recognition
FRAME_DELAY = 20

TRAINING_TASK_TIMEOUT = 20
RECOGNITION_TASK_TIMEOUT = 20

CONFIDENCE_THRESHOLD = 2000
SUCCESS_RATE_THRESHOLD = 0.7

NUM_SAMPLED_TRAINING_IMAGES = 5
NUM_SAMPLED_TESTING_IMAGES  = 3

HAAR_FACES         = 'haarcascade_frontalface_alt.xml'
HAAR_SCALE_FACTOR  = 1.3
HAAR_MIN_NEIGHBORS = 4
HAAR_MIN_SIZE      = (30, 30)

FACE_WIDTH  = 92
FACE_HEIGHT = 112
