# serial
SERIAL_DEVICE_PATH   = '/dev/ttyAMA0'
SERIAL_BAUDRATE = 115200

# face recognition
TRAINING_TASK_TIMEOUT = 30
RECOGNITION_TASK_TIMEOUT = 30

CONFIDENCE_THRESHOLD = 3000
SUCCESS_RATE_THRESHOLD = 0.7

NUM_SAMPLED_TRAINING_IMAGES = 10
NUM_SAMPLED_TESTING_IMAGES  = 5

HAAR_FACES         = 'haarcascade_frontalface_alt.xml'
HAAR_SCALE_FACTOR  = 1.3
HAAR_MIN_NEIGHBORS = 4
HAAR_MIN_SIZE      = (30, 30)

FACE_WIDTH  = 92
FACE_HEIGHT = 112
